import { useState } from "react";
import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import {
  Alert, AssetCard, Breadcrumbs, BudgetMetric, Button, Checkbox, CoverageStatus, Drawer, DropdownMenu, EchelonTreeItem, EmptyState, ErrorState,
  LoadingState, Modal, Navigation, ObjectInspector, PageHeader, Pagination, Popover, Radio, Search, SegmentedControl, Select, SuccessState, Switch,
  Table, Tabs, Tag, Toast, Tooltip, WarningStack,
} from "./index";

const meta = { title: "Components/Complete UI Kit" } satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;

const card = "grid gap-4 rounded-[var(--fortis-radii-panel)] border border-[var(--fortis-semantic-light-border-default)] bg-[var(--fortis-semantic-light-background-surface)] p-5";
const assets = [{ id: "radar", name: "РЛС «Барьер»", type: "Радиолокация", metrics: "4.5 км" }, { id: "mog", name: "МОГ №1", type: "Мобильная группа", metrics: "12.4 млн ₽" }];

export const CoreAndFeedback: Story = { render: function CoreAndFeedback() {
  const [query, setQuery] = useState(""); const [mode, setMode] = useState("map"); const [switchOn, setSwitchOn] = useState(true); const [selectedAsset, setSelectedAsset] = useState("radar");
  return <div className="grid w-[min(70rem,calc(100vw-4rem))] gap-6">
    <PageHeader actions={<Button>Сохранить</Button>} breadcrumbs={[{ label: "Fortis", href: "/" }, { label: "UI Kit" }]} description="Полный набор shared-компонентов по утверждённому контракту." eyebrow="Design system" title="Fortis UI Kit" />
    <section className={card}><h2 className="font-semibold">Выбор и ввод</h2><div className="grid gap-4 md:grid-cols-2"><Select label="Эшелон" onValueChange={setSelectedAsset} options={[{ value: "radar", label: "L2 · Ближняя зона" }, { value: "mog", label: "L3 · Средняя зона" }]} value={selectedAsset} /><Search label="Поиск активов" onQueryChange={setQuery} query={query} resultLabel={query ? "Найдено 2 актива" : "Все активы"} /><Checkbox defaultChecked description="Объекты остаются в расчёте." label="Показывать покрытие" /><Radio defaultValue="basic" label="Сценарий" options={[{ value: "basic", label: "Базовый" }, { value: "extended", label: "Расширенный" }]} /><Switch checked={switchOn} description="Изменение применяется сразу." label="Эшелон видим на карте" onCheckedChange={setSwitchOn} /><SegmentedControl items={[{ value: "map", label: "Карта" }, { value: "list", label: "Список" }]} onValueChange={setMode} value={mode} /></div><div className="flex flex-wrap gap-2"><Tag label="РЛС" removable onRemove={() => undefined} selected /><Tag label="L2" /></div></section>
    <section className={card}><h2 className="font-semibold">Навигация и действия</h2><Navigation currentId="workspace" items={[{ id: "workspace", label: "Рабочая область", href: "#workspace" }, { id: "reports", label: "Отчёты", href: "#reports" }]} orientation="horizontal" /><Tabs items={[{ value: "overview", label: "Обзор", content: <p className="text-sm text-[var(--fortis-semantic-light-text-secondary)]">Контекст активного варианта.</p> }, { value: "objects", label: "Объекты", content: <p className="text-sm text-[var(--fortis-semantic-light-text-secondary)]">Список размещённых объектов.</p> }]} /><DropdownMenu items={[{ id: "edit", label: "Изменить" }, { id: "delete", label: "Удалить", destructive: true }]} trigger={<Button variant="secondary">Действия</Button>} /><Popover title="Сводка" trigger={<Button variant="secondary">Открыть сводку</Button>}><p className="text-sm">Проверка покрытий завершена.</p></Popover><Tooltip content="Показывает дополнительные действия"><Button variant="quiet">Подсказка</Button></Tooltip></section>
    <section className={card}><h2 className="font-semibold">Обратная связь</h2><Alert action={<Button size="sm" variant="quiet">Открыть</Button>} title="Нужно внимание" tone="warning">Один сектор требует проверки.</Alert><LoadingState label="Пересчёт покрытия" /><EmptyState description="Добавьте первое средство, чтобы начать расчёт." title="Пока нет объектов" /><ErrorState action={<Button size="sm">Повторить</Button>} description="Сервер не ответил в отведённое время." title="Не удалось загрузить данные" /><SuccessState description="Версия доступна участникам проекта." title="Вариант сохранён" /></section>
  </div>;
} };

export const DataAndGIS: Story = { render: function DataAndGIS() { const [page, setPage] = useState(1); return <div className="grid w-[min(70rem,calc(100vw-4rem))] gap-6"><section className={card}><h2 className="font-semibold">Данные</h2><Table caption="Активы проекта" columns={[{ id: "name", header: "Актив", cell: (asset) => asset.name }, { id: "type", header: "Тип", cell: (asset) => asset.type }, { id: "metrics", header: "Дальность", cell: (asset) => asset.metrics, align: "right" }]} onRowSelect={() => undefined} rows={assets} /><Pagination onPageChange={setPage} page={page} pageCount={3} /></section><section className="grid gap-4 lg:grid-cols-3"><AssetCard asset={assets[0]} onSelect={() => undefined} selected /><div className={card} role="tree"><EchelonTreeItem expanded level={1} node={{ id: "l2", label: "L2 · Ближняя зона", meta: "2 объекта", children: [{ id: "radar", label: "РЛС «Барьер»", meta: "4.5 км" }] }} onSelect={() => undefined} /></div><ObjectInspector object={{ id: "radar", name: "РЛС «Барьер»", type: "Радиолокация", properties: [{ label: "Количество", value: "2 ед." }, { label: "Радиус", value: "4.5 км" }] }} saveState="saved" /></section><section className="grid gap-4 md:grid-cols-3"><BudgetMetric label="Стоимость" value={34700000} /><CoverageStatus basis="По активным объектам" status="partial" value={74} variant="bar" /><WarningStack warnings={[{ id: "sector", title: "Проверьте северный сектор", description: "Пересечение с ограниченной зоной." }]} /></section><Breadcrumbs items={[{ label: "Проекты", href: "#projects" }, { label: "Завод Альфа" }]} /></div>; } };

export const Overlays: Story = { render: function Overlays() { const [modalOpen, setModalOpen] = useState(false); const [drawerOpen, setDrawerOpen] = useState(false); const [toastOpen, setToastOpen] = useState(false); return <div className="flex w-[min(40rem,calc(100vw-4rem))] flex-wrap gap-3"><Button onClick={() => setModalOpen(true)}>Открыть Modal</Button><Button onClick={() => setDrawerOpen(true)} variant="secondary">Открыть Drawer</Button><Button onClick={() => setToastOpen(true)} variant="quiet">Показать Toast</Button><Modal footer={<><Button onClick={() => setModalOpen(false)} variant="secondary">Отмена</Button><Button onClick={() => setModalOpen(false)}>Сохранить</Button></>} onOpenChange={setModalOpen} open={modalOpen} title="Сохранить вариант"><p className="text-sm text-[var(--fortis-semantic-light-text-secondary)]">Изменения будут доступны команде.</p></Modal><Drawer onOpenChange={setDrawerOpen} open={drawerOpen} title="Инспектор"><ObjectInspector object={{ id: "mog", name: "МОГ №1", type: "Мобильная группа" }} /></Drawer><Toast description="Новая конфигурация доступна в списке вариантов." onOpenChange={setToastOpen} open={toastOpen} title="Вариант сохранён" tone="success" /></div>; } };
