import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { useState } from "react";
import { AssetCard, Breadcrumbs, BudgetMetric, Button, CoverageStatus, EchelonTreeItem, EmptyState, ErrorState, LoadingState, Navigation, PageHeader, Pagination, SuccessState, Table, WarningStack } from "./index";

const meta = { title: "Components/Data, navigation & domain" } satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;

function DataExample() { const [page, setPage] = useState(1); return <section className="fortis-storybook-panel"><Table columns={[{ key: "asset", label: "Актив" }, { key: "layer", label: "Эшелон" }, { key: "state", label: "Статус" }, { key: "cost", label: "Стоимость, ₽" }]} rows={[{ asset: "МОГ — пост №1", cost: "12 480 000", id: "1", layer: "L2", state: "В проекте" }, { asset: "РЛС — север", cost: "34 700 000", id: "2", layer: "L3", selected: true, state: "Проверить" }]} /><Pagination onPageChange={setPage} page={page} pageCount={3} /></section>; }
export const Data: Story = { render: () => <DataExample /> };
export const NavigationAndStates: Story = { render: () => <section className="fortis-storybook-panel"><Navigation currentId="gis" items={[{ href: "#", id: "overview", label: "Обзор" }, { href: "#", id: "gis", label: "GIS Workspace" }, { href: "#", id: "cost", label: "Смета" }]} /><Breadcrumbs items={[{ href: "#", label: "Проекты" }, { href: "#", label: "Завод Альфа" }, { label: "GIS Workspace" }]} /><PageHeader actions={<><Button variant="secondary">Сравнить</Button><Button>Сохранить версию</Button></>} description="21 актив · 4 эшелона · обновлено в 14:32" eyebrow="FP-ALPHA-012 · версия 12" title="Завод Альфа" /><div className="fortis-storybook-grid"><EmptyState action={<Button>Открыть библиотеку</Button>} description="Добавьте первый актив в выбранный эшелон." title="Нет активов" /><LoadingState label="Считаем покрытие" /><ErrorState description="Проверьте соединение и повторите запрос." onRetry={() => undefined} title="Данные недоступны" /><SuccessState action={<Button variant="secondary">Сравнить</Button>} description="v12 · Андрей Морозов · 14:32" title="Версия сохранена" /></div></section> };
export const Domain: Story = { render: () => <section className="fortis-storybook-grid"><AssetCard meta="Мобильная огневая группа · 3,2 км" selected status="Активен" title="МОГ — пост №1" /><div className="fortis-storybook-panel" role="tree"><EchelonTreeItem count={6} label="Периметр" level="L1" /><EchelonTreeItem count={9} label="Ближняя зона" level="L2" selected /><EchelonTreeItem count={2} label="Внешняя зона" level="L4" warning /></div><BudgetMetric comparison="92% лимита · остаток ₽ 15,24 млн" label="Стоимость конфигурации" status="warning" value="₽ 184 760 000" /><CoverageStatus entries={[{ label: "L1 · Периметр", pattern: "solid", value: "96%" }, { label: "L2 · Ближняя", pattern: "dashed", value: "87%" }, { label: "L3 · Средняя", pattern: "dotted", value: "82%" }]} /><WarningStack warnings={[{ action: <Button size="sm" variant="quiet">Показать</Button>, detail: "Северный сектор", title: "Покрытие 71%" }, { action: <Button size="sm" variant="quiet">Проверить</Button>, detail: "21 день", title: "Цена устарела" }]} /></section> };
