import { type ReactNode } from "react";

import { cn } from "@/lib/utils";
import { Badge } from "./badge";
import { Button } from "./button";
import { Icon } from "./icon";
import { IconButton } from "./icon-button";
import { InlineMessage } from "./inline-message";
import { SaveIndicator, type SaveState } from "./save-indicator";
import { Status, type StatusTone } from "./status";

export interface ColumnDef<Row> { id: string; header: string; cell: (row: Row) => ReactNode; align?: "left" | "right"; sortable?: boolean; }
export interface TableProps<Row extends { id: string }> { columns: ColumnDef<Row>[]; rows: Row[]; caption: string; selectedIds?: ReadonlySet<string>; onRowSelect?: (row: Row) => void; loading?: boolean; emptyMessage?: string; }
export function Table<Row extends { id: string }>({ caption, columns, emptyMessage = "Нет данных", loading = false, onRowSelect, rows, selectedIds }: TableProps<Row>) { return <div className="w-full overflow-x-auto rounded-[var(--fortis-radii-panel)] border border-[var(--fortis-semantic-light-border-default)]"><table className="w-full min-w-[32rem] border-collapse text-sm"><caption className="sr-only">{caption}</caption><thead className="bg-[var(--fortis-component-table-header-surface)]"><tr>{columns.map((column) => <th className={cn("h-[var(--fortis-component-table-row-height)] px-3 text-left text-[0.8125rem] font-semibold text-[var(--fortis-semantic-light-text-secondary)]", column.align === "right" && "text-right")} key={column.id} scope="col">{column.header}</th>)}</tr></thead><tbody>{loading ? <tr><td className="p-4" colSpan={columns.length}><span aria-busy="true" aria-live="polite" className="flex items-center gap-2 text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]"><Icon className="animate-spin" decorative name="status.loading" size={16} />Загрузка…</span></td></tr> : rows.length ? rows.map((row) => <tr aria-selected={selectedIds?.has(row.id) || undefined} className={cn("border-t border-[var(--fortis-semantic-light-border-default)]", onRowSelect && "cursor-pointer hover:bg-[var(--fortis-semantic-light-state-hover-surface)]", selectedIds?.has(row.id) && "bg-[var(--fortis-component-table-row-selected-surface)] shadow-[inset_3px_0_0_var(--fortis-component-table-row-selected-border)]")} key={row.id} onClick={() => onRowSelect?.(row)}>{columns.map((column) => <td className={cn("h-[var(--fortis-component-table-row-height)] px-3", column.align === "right" && "text-right tabular-nums")} key={column.id}>{column.cell(row)}</td>)}</tr>) : <tr><td className="p-6 text-center text-[var(--fortis-semantic-light-text-secondary)]" colSpan={columns.length}>{emptyMessage}</td></tr>}</tbody></table></div>; }

export interface PaginationProps { page: number; pageCount: number; onPageChange?: (page: number) => void; disabled?: boolean; }
export function Pagination({ disabled = false, onPageChange, page, pageCount }: PaginationProps) { const pages = Array.from({ length: pageCount }, (_, index) => index + 1); return <nav aria-label="Страницы" className="flex flex-wrap items-center gap-1"><Button disabled={disabled || page <= 1} onClick={() => onPageChange?.(page - 1)} size="sm" variant="secondary">Назад</Button>{pages.map((nextPage) => <button aria-current={nextPage === page ? "page" : undefined} aria-label={`Страница ${nextPage}`} className={cn("min-h-10 min-w-10 rounded-[var(--fortis-radii-control)] px-2 text-sm font-medium outline-none hover:bg-[var(--fortis-semantic-light-state-hover-surface)] focus-visible:ring-2 focus-visible:ring-[var(--fortis-component-button-focus-ring)]", nextPage === page && "bg-[var(--fortis-semantic-light-background-selected)] text-[var(--fortis-semantic-light-text-link)]")} disabled={disabled} key={nextPage} onClick={() => onPageChange?.(nextPage)} type="button">{nextPage}</button>)}<Button disabled={disabled || page >= pageCount} onClick={() => onPageChange?.(page + 1)} size="sm" variant="secondary">Далее</Button></nav>; }

export interface NavItem { id: string; label: string; href: string; icon?: ReactNode; disabled?: boolean; }
export interface NavigationProps { items: NavItem[]; currentId: string; orientation?: "horizontal" | "vertical"; collapsed?: boolean; label?: string; }
export function Navigation({ collapsed = false, currentId, items, label = "Навигация", orientation = "vertical" }: NavigationProps) { return <nav aria-label={label}><ul className={cn("flex gap-1", orientation === "vertical" ? "flex-col" : "flex-wrap")}>{items.map((item) => <li key={item.id}><a aria-current={item.id === currentId ? "page" : undefined} aria-label={collapsed ? item.label : undefined} className={cn("flex min-h-[var(--fortis-density-modes-active-control-height)] items-center gap-2 rounded-[var(--fortis-radii-control)] px-3 text-sm font-medium outline-none hover:bg-[var(--fortis-component-navigation-item-hover-surface)] focus-visible:ring-2 focus-visible:ring-[var(--fortis-component-navigation-item-focus-ring)]", item.id === currentId ? "bg-[var(--fortis-component-navigation-item-active-surface)] text-[var(--fortis-component-navigation-item-active-text)] shadow-[inset_3px_0_0_var(--fortis-component-navigation-item-active-border)]" : "text-[var(--fortis-component-navigation-item-default-text)]", item.disabled && "pointer-events-none opacity-[var(--fortis-semantic-light-state-disabled-opacity)]", collapsed && "min-w-[var(--fortis-density-modes-active-control-height)] justify-center px-0")} href={item.href}>{item.icon}{collapsed ? <span className="sr-only">{item.label}</span> : <span>{item.label}</span>}</a></li>)}</ul></nav>; }

export interface BreadcrumbItem { label: string; href?: string; }
export function Breadcrumbs({ items, maxItems }: { items: BreadcrumbItem[]; maxItems?: number }) { const visibleItems = maxItems && items.length > maxItems ? [items[0], ...items.slice(-(maxItems - 1))] : items; return <nav aria-label="Хлебные крошки"><ol className="flex flex-wrap items-center gap-1 text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]">{visibleItems.map((item, index) => <li className="flex items-center gap-1" key={`${item.label}-${index}`}>{index ? <Icon decorative name="navigation.chevronRight" size={14} /> : null}{index === visibleItems.length - 1 ? <span aria-current="page" className="font-medium text-[var(--fortis-semantic-light-text-primary)]">{item.label}</span> : item.href ? <a className="rounded px-1 py-0.5 outline-none hover:underline focus-visible:ring-2 focus-visible:ring-[var(--fortis-component-button-focus-ring)]" href={item.href}>{item.label}</a> : <span>{item.label}</span>}</li>)}</ol></nav>; }

export interface PageHeaderProps { title: string; description?: ReactNode; eyebrow?: ReactNode; breadcrumbs?: BreadcrumbItem[]; actions?: ReactNode; metadata?: ReactNode; compact?: boolean; }
export function PageHeader({ actions, breadcrumbs, compact = false, description, eyebrow, metadata, title }: PageHeaderProps) { return <header className={cn("grid gap-4 border-b border-[var(--fortis-semantic-light-border-default)]", compact ? "pb-4" : "pb-6")}>{breadcrumbs ? <Breadcrumbs items={breadcrumbs} /> : null}<div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0">{eyebrow ? <p className="text-[0.8125rem] font-semibold text-[var(--fortis-semantic-light-text-link)]">{eyebrow}</p> : null}<h1 className={cn("font-semibold tracking-tight", compact ? "text-2xl" : "text-3xl")}>{title}</h1>{description ? <div className="mt-2 max-w-3xl text-sm leading-6 text-[var(--fortis-semantic-light-text-secondary)]">{description}</div> : null}{metadata ? <div className="mt-3">{metadata}</div> : null}</div>{actions ? <div className="flex flex-wrap gap-2">{actions}</div> : null}</div></header>; }

export interface FortisAsset { id: string; name: string; type: string; metrics?: ReactNode; status?: { label: string; tone?: StatusTone }; }
export interface AssetCardProps { asset: FortisAsset; selected?: boolean; disabled?: boolean; availability?: "available" | "limited" | "unavailable"; variant?: "catalog" | "placed" | "compact"; onSelect?: (asset: FortisAsset) => void; action?: ReactNode; }
export function AssetCard({ action, asset, availability = "available", disabled = false, onSelect, selected = false, variant = "catalog" }: AssetCardProps) { const isInteractive = Boolean(onSelect); return <article className={cn("min-w-0 rounded-[var(--fortis-radii-panel)] border p-4", selected ? "border-[var(--fortis-semantic-light-border-selected)] bg-[var(--fortis-semantic-light-background-selected)]" : "border-[var(--fortis-semantic-light-border-default)] bg-[var(--fortis-semantic-light-background-surface)]", disabled && "opacity-[var(--fortis-semantic-light-state-disabled-opacity)]", variant === "compact" ? "min-h-[4.5rem]" : "min-h-24")}><div className="flex items-start gap-3"><button aria-pressed={selected || undefined} className={cn("grid min-w-0 flex-1 gap-1 text-left outline-none", isInteractive && "cursor-pointer focus-visible:ring-2 focus-visible:ring-[var(--fortis-component-button-focus-ring)]")} disabled={disabled || !isInteractive} onClick={() => onSelect?.(asset)} type="button"><span className="flex items-center gap-2"><span aria-hidden="true" className="grid size-8 place-items-center rounded-[var(--fortis-radii-control)] bg-[var(--fortis-semantic-light-background-subtle)] text-sm font-semibold text-[var(--fortis-semantic-light-text-link)]">{asset.type.slice(0, 2)}</span><span className="min-w-0"><span className="block truncate font-semibold">{asset.name}</span><span className="block text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]">{asset.type}</span></span></span>{asset.metrics ? <span className="text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]">{asset.metrics}</span> : null}</button>{action}</div>{availability !== "available" || asset.status ? <div className="mt-3 flex flex-wrap gap-2">{availability !== "available" ? <Badge>{availability === "limited" ? "Ограничено" : "Недоступно"}</Badge> : null}{asset.status ? <Status label={asset.status.label} tone={asset.status.tone} /> : null}</div> : null}</article>; }

export interface EchelonNode { id: string; label: string; meta?: ReactNode; children?: EchelonNode[]; warning?: boolean; }
export interface EchelonTreeItemProps { node: EchelonNode; level: number; expanded?: boolean; selected?: boolean; disabled?: boolean; onExpandedChange?: (expanded: boolean) => void; onSelect?: (node: EchelonNode) => void; }
export function EchelonTreeItem({ disabled = false, expanded = false, level, node, onExpandedChange, onSelect, selected = false }: EchelonTreeItemProps) { const hasChildren = Boolean(node.children?.length); return <div role="treeitem" aria-disabled={disabled || undefined} aria-expanded={hasChildren ? expanded : undefined} aria-level={level} aria-selected={selected}><div className={cn("flex min-h-[var(--fortis-density-modes-active-row-height)] items-center gap-1 rounded-[var(--fortis-radii-control)]", selected && "bg-[var(--fortis-semantic-light-background-selected)]")} style={{ paddingLeft: `${Math.max(0, level - 1) * 16}px` }}>{hasChildren ? <IconButton icon={expanded ? "navigation.chevronDown" : "navigation.chevronRight"} label={expanded ? `Свернуть ${node.label}` : `Развернуть ${node.label}`} onClick={() => onExpandedChange?.(!expanded)} size="sm" variant="quiet" /> : <span className="w-10" />}{<button className="flex min-w-0 flex-1 items-center gap-2 rounded px-1 text-left text-sm outline-none focus-visible:ring-2 focus-visible:ring-[var(--fortis-component-button-focus-ring)] disabled:opacity-[var(--fortis-semantic-light-state-disabled-opacity)]" disabled={disabled} onClick={() => onSelect?.(node)} type="button"><span className="truncate font-medium">{node.label}</span>{node.meta ? <span className="ml-auto shrink-0 text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]">{node.meta}</span> : null}{node.warning ? <Icon className="shrink-0 text-[var(--fortis-semantic-light-status-warning-text)]" label="Есть предупреждение" name="status.warning" size={16} /> : null}</button>}</div>{hasChildren && expanded ? <div role="group">{node.children?.map((child) => <EchelonTreeItem key={child.id} level={level + 1} node={child} onSelect={onSelect} />)}</div> : null}</div>; }

export interface FortisObject { id: string; name: string; type: string; status?: { label: string; tone?: StatusTone }; properties?: Array<{ label: string; value: ReactNode }>; }
export interface ObjectInspectorProps { object: FortisObject | null; mode?: "view" | "edit"; loading?: boolean; dirty?: boolean; saveState?: SaveState; onClose?: () => void; children?: ReactNode; }
export function ObjectInspector({ children, dirty = false, loading = false, mode = "view", object, onClose, saveState }: ObjectInspectorProps) { if (loading) return <aside aria-label="Инспектор объекта" className="min-w-[17.5rem] p-4"><div className="h-6 w-1/2 animate-pulse rounded bg-[var(--fortis-semantic-light-background-muted)]" /></aside>; if (!object) return <aside aria-label="Инспектор объекта" className="grid min-w-[17.5rem] content-center gap-2 p-5"><h2 className="font-semibold">Ничего не выбрано</h2><p className="text-sm text-[var(--fortis-semantic-light-text-secondary)]">Выберите объект на карте или в дереве.</p></aside>; return <aside aria-label="Инспектор объекта" className="grid min-w-[17.5rem] content-start gap-5 bg-[var(--fortis-semantic-light-background-surface)] p-5"><header className="flex items-start justify-between gap-3"><div><p className="text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]">{object.type}</p><h2 className="text-lg font-semibold">{object.name}</h2></div>{onClose ? <IconButton icon="action.close" label="Закрыть инспектор" onClick={onClose} size="sm" variant="quiet" /> : null}</header>{object.status ? <Status label={object.status.label} tone={object.status.tone} /> : null}<dl className="grid gap-3">{object.properties?.map((property) => <div className="flex justify-between gap-4 border-b border-[var(--fortis-semantic-light-border-default)] pb-2" key={property.label}><dt className="text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]">{property.label}</dt><dd className="text-right text-sm font-medium">{property.value}</dd></div>)}</dl>{children}{dirty ? <InlineMessage tone="warning">Есть несохранённые изменения.</InlineMessage> : null}{saveState ? <SaveIndicator state={saveState} /> : null}<p className="text-[0.6875rem] text-[var(--fortis-semantic-light-text-secondary)]">Режим: {mode === "edit" ? "Редактирование" : "Просмотр"}</p></aside>; }

export interface BudgetMetricProps { label: string; value: number | null; currency?: string; status?: "neutral" | "warning" | "danger"; comparison?: number; variant?: "budget" | "cost" | "remaining" | "delta"; }
export function BudgetMetric({ comparison, currency = "₽", label, status = "neutral", value, variant = "cost" }: BudgetMetricProps) { const formattedValue = value === null ? "—" : new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 0 }).format(value); const tone = status === "danger" ? "danger" : status === "warning" ? "warning" : "neutral"; return <section className="grid min-h-16 gap-1 rounded-[var(--fortis-radii-control)] border border-[var(--fortis-semantic-light-border-default)] bg-[var(--fortis-semantic-light-background-subtle)] p-3"><span className="text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]">{label}</span><span className={cn("font-mono text-lg font-semibold", tone === "danger" && "text-[var(--fortis-semantic-light-status-danger-text)]", tone === "warning" && "text-[var(--fortis-semantic-light-status-warning-text)]")}>{formattedValue} {value === null ? "Нет расчёта" : currency}</span>{comparison !== undefined ? <span className="text-[0.6875rem] text-[var(--fortis-semantic-light-text-secondary)]">Отклонение: {new Intl.NumberFormat("ru-RU").format(comparison)} {currency}</span> : null}<span className="sr-only">Тип метрики: {variant}</span></section>; }

export interface CoverageStatusProps { value: number | null; status: "unknown" | "good" | "partial" | "critical"; basis: string; stale?: boolean; variant?: "inline" | "metric" | "bar"; }
export function CoverageStatus({ basis, stale = false, status, value, variant = "metric" }: CoverageStatusProps) { const tone: StatusTone = status === "good" ? "success" : status === "partial" ? "warning" : status === "critical" ? "danger" : "neutral"; const label = value === null ? "Нет данных" : `Покрытие ${value}%`; return <section className={cn("grid gap-2", variant === "metric" && "min-h-[var(--fortis-density-modes-active-control-height)] rounded-[var(--fortis-radii-control)] border border-[var(--fortis-semantic-light-border-default)] p-3")}><div className="flex flex-wrap items-center justify-between gap-2"><Status label={label} tone={tone} /><span className="text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]">{basis}{stale ? " · требуется обновление" : ""}</span></div>{variant === "bar" && value !== null ? <div aria-label={label} aria-valuemax={100} aria-valuemin={0} aria-valuenow={value} className="h-2 overflow-hidden rounded-full bg-[var(--fortis-semantic-light-background-muted)]" role="progressbar"><span className={cn("block h-full rounded-full", tone === "success" ? "bg-[var(--fortis-semantic-light-status-success-text)]" : tone === "warning" ? "bg-[var(--fortis-semantic-light-status-warning-text)]" : "bg-[var(--fortis-semantic-light-status-danger-text)]")} style={{ width: `${value}%` }} /></div> : null}</section>; }

export interface FortisWarning { id: string; title: string; description?: ReactNode; action?: ReactNode; tone?: Exclude<StatusTone, "neutral">; }
export interface WarningStackProps { warnings: FortisWarning[]; maxVisible?: number; expanded?: boolean; onExpandedChange?: (expanded: boolean) => void; }
export function WarningStack({ expanded = false, maxVisible = 3, onExpandedChange, warnings }: WarningStackProps) { const visibleWarnings = expanded ? warnings : warnings.slice(0, maxVisible); if (!warnings.length) return null; return <section aria-label="Предупреждения" className="grid gap-2 rounded-[var(--fortis-radii-panel)] border border-[var(--fortis-component-warning-stack-border)] bg-[var(--fortis-component-warning-stack-surface)] p-3"><div className="flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">Предупреждения</h2><span aria-live="polite" className="text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]">{warnings.length}</span></div><ul className="grid gap-2">{visibleWarnings.map((warning) => <li className="rounded-[var(--fortis-radii-control)] bg-[var(--fortis-component-warning-stack-primary-surface)] p-3" key={warning.id}><div className="flex gap-2"><Icon className="mt-0.5 shrink-0 text-[var(--fortis-component-warning-stack-primary-text)]" decorative name={warning.tone === "danger" ? "status.error" : "status.warning"} size={16} /><div className="min-w-0"><p className="text-sm font-semibold">{warning.title}</p>{warning.description ? <div className="mt-1 text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]">{warning.description}</div> : null}{warning.action ? <div className="mt-2">{warning.action}</div> : null}</div></div></li>)}</ul>{warnings.length > maxVisible ? <button aria-expanded={expanded} className="min-h-10 rounded-[var(--fortis-radii-control)] text-left text-sm font-medium text-[var(--fortis-semantic-light-text-link)] outline-none focus-visible:ring-2 focus-visible:ring-[var(--fortis-component-button-focus-ring)]" onClick={() => onExpandedChange?.(!expanded)} type="button">{expanded ? "Свернуть" : `Показать ещё ${warnings.length - maxVisible}`}</button> : null}</section>; }
