import type { ComponentType, SVGProps } from "react";
import {
  AlertTriangle,
  ArrowLeft,
  Building2,
  Calculator,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChartNoAxesCombined,
  CircleEllipsis,
  CloudOff,
  Copy,
  Crosshair,
  DollarSign,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  GripVertical,
  Layers3,
  LoaderCircle,
  LocateFixed,
  Map,
  MapPinned,
  Maximize2,
  Menu,
  Minus,
  Move,
  MoreHorizontal,
  Network,
  PauseCircle,
  Pencil,
  PlayCircle,
  Plus,
  Radar,
  RadioTower,
  RefreshCw,
  RotateCcw,
  Ruler,
  Save,
  Search,
  Shield,
  SatelliteDish,
  Trash2,
  Wrench,
  Zap,
  X,
  XCircle,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

type LucideIcon = ComponentType<SVGProps<SVGSVGElement>>;

const icons = {
  "action.add": Plus,
  "action.close": X,
  "action.collapse": ChevronDown,
  "action.delete": Trash2,
  "action.duplicate": Copy,
  "action.edit": Pencil,
  "action.expand": Maximize2,
  "action.export": Download,
  "action.locate": LocateFixed,
  "action.more": Ellipsis,
  "action.pause": PauseCircle,
  "action.play": PlayCircle,
  "action.refresh": RefreshCw,
  "action.save": Save,
  "action.search": Search,
  "action.drag": GripVertical,
  "action.visibility-off": EyeOff,
  "action.visibility-on": Eye,
  "map.basemap": Map,
  "map.layers": Layers3,
  "map.measure": Ruler,
  "map.pan": Move,
  "map.coordinates": Crosshair,
  "map.reset": RotateCcw,
  "map.zoom-in": ZoomIn,
  "map.zoom-out": ZoomOut,
  "navigation.analysis": ChartNoAxesCombined,
  "navigation.back": ArrowLeft,
  "navigation.calculator": Calculator,
  "navigation.chevron-down": ChevronDown,
  "navigation.chevron-left": ChevronLeft,
  "navigation.chevron-right": ChevronRight,
  "navigation.chevron-up": ChevronUp,
  "navigation.map": MapPinned,
  "navigation.menu": Menu,
  "navigation.scenario": Radar,
  "asset.camera": Camera,
  "asset.command-center": Building2,
  "asset.detection": SatelliteDish,
  "asset.infrastructure": Wrench,
  "asset.interceptor": Crosshair,
  "asset.jamming": RadioTower,
  "asset.network": Network,
  "asset.protection": Shield,
  "metric.cost": DollarSign,
  "metric.response": Zap,
  "status.error": XCircle,
  "status.info": CircleEllipsis,
  "status.loading": LoaderCircle,
  "status.offline": CloudOff,
  "status.success": CheckCircle2,
  "status.warning": AlertTriangle,
  check: Check,
  minus: Minus,
  more: MoreHorizontal,
} as const satisfies Record<string, LucideIcon>;

export type FortisIconName = keyof typeof icons;

type IconProps = SVGProps<SVGSVGElement> & {
  decorative?: boolean;
  name: FortisIconName;
  size?: number;
};

export function Icon({ decorative = false, name, size = 16, ...props }: IconProps) {
  const Glyph = icons[name];
  return <Glyph aria-hidden={decorative || undefined} focusable="false" height={size} width={size} {...props} />;
}
