"use client";

import { useId, type ReactNode } from "react";
import { Dialog, DropdownMenu as DropdownPrimitive, Popover as PopoverPrimitive, Toast as ToastPrimitive, Tooltip as TooltipPrimitive } from "radix-ui";

import { cn } from "@/lib/utils";
import { Button } from "./button";
import { Icon, type FortisIconName } from "./icon";
import { IconButton } from "./icon-button";
import type { StatusTone } from "./status";

const toneClasses: Record<Exclude<StatusTone, "neutral">, string> = {
  info: "border-[var(--fortis-semantic-light-status-info-text)]/30 bg-[var(--fortis-semantic-light-status-info-surface)] text-[var(--fortis-semantic-light-status-info-text)]",
  success: "border-[var(--fortis-semantic-light-status-success-text)]/30 bg-[var(--fortis-semantic-light-status-success-surface)] text-[var(--fortis-semantic-light-status-success-text)]",
  warning: "border-[var(--fortis-semantic-light-status-warning-text)]/30 bg-[var(--fortis-semantic-light-status-warning-surface)] text-[var(--fortis-semantic-light-status-warning-text)]",
  danger: "border-[var(--fortis-semantic-light-status-danger-text)]/30 bg-[var(--fortis-semantic-light-status-danger-surface)] text-[var(--fortis-semantic-light-status-danger-text)]",
};
const toneIcon: Record<Exclude<StatusTone, "neutral">, FortisIconName> = { info: "status.loading", success: "status.success", warning: "status.warning", danger: "status.error" };

export interface AlertProps { tone?: Exclude<StatusTone, "neutral">; title?: string; children: ReactNode; action?: ReactNode; dismissible?: boolean; onDismiss?: () => void; variant?: "inline" | "banner"; }
export function Alert({ action, children, dismissible = false, onDismiss, title, tone = "info", variant = "inline" }: AlertProps) { return <section className={cn("flex min-w-0 items-start gap-3 rounded-[var(--fortis-radii-control)] border p-4", toneClasses[tone], variant === "banner" && "rounded-none border-x-0")} role={tone === "danger" ? "alert" : "status"}><Icon className="mt-0.5 shrink-0" decorative name={toneIcon[tone]} size={18} /><div className="min-w-0 flex-1">{title ? <h2 className="font-semibold">{title}</h2> : null}<div className={title ? "mt-1 text-sm leading-5" : "text-sm leading-5"}>{children}</div>{action ? <div className="mt-3">{action}</div> : null}</div>{dismissible ? <IconButton icon="action.close" label="Закрыть сообщение" onClick={onDismiss} size="sm" variant="quiet" /> : null}</section>; }

export interface TooltipProps { content: ReactNode; children: ReactNode; side?: "top" | "right" | "bottom" | "left"; delay?: number; }
export function Tooltip({ children, content, delay = 400, side = "top" }: TooltipProps) { return <TooltipPrimitive.Provider delayDuration={delay}><TooltipPrimitive.Root><TooltipPrimitive.Trigger asChild>{children}</TooltipPrimitive.Trigger><TooltipPrimitive.Portal><TooltipPrimitive.Content className="z-[var(--fortis-primitive-z-index-toast)] max-w-[17.5rem] rounded-[var(--fortis-radii-control)] bg-[var(--fortis-primitive-color-neutral-900)] px-2.5 py-1.5 text-[0.8125rem] text-white shadow-[var(--fortis-elevation-overlay)]" side={side}>{content}<TooltipPrimitive.Arrow className="fill-[var(--fortis-primitive-color-neutral-900)]" /></TooltipPrimitive.Content></TooltipPrimitive.Portal></TooltipPrimitive.Root></TooltipPrimitive.Provider>; }

export interface MenuItem { id: string; label: string; disabled?: boolean; destructive?: boolean; checked?: boolean; onSelect?: () => void; }
export interface DropdownMenuProps { trigger: ReactNode; items: MenuItem[]; label?: string; }
export function DropdownMenu({ items, label = "Дополнительные действия", trigger }: DropdownMenuProps) { return <DropdownPrimitive.Root><DropdownPrimitive.Trigger aria-label={label} asChild>{trigger}</DropdownPrimitive.Trigger><DropdownPrimitive.Portal><DropdownPrimitive.Content align="end" className="z-[var(--fortis-primitive-z-index-dropdown)] min-w-52 rounded-[var(--fortis-radii-panel)] border border-[var(--fortis-semantic-light-border-default)] bg-[var(--fortis-semantic-light-background-surface)] p-1 shadow-[var(--fortis-elevation-overlay)]"><DropdownPrimitive.Label className="px-2 py-1.5 text-[0.6875rem] font-semibold uppercase tracking-wide text-[var(--fortis-semantic-light-text-secondary)]">{label}</DropdownPrimitive.Label>{items.map((item) => <DropdownPrimitive.Item className={cn("flex min-h-10 cursor-default items-center gap-2 rounded-[var(--fortis-radii-control)] px-2 text-sm outline-none data-[highlighted]:bg-[var(--fortis-semantic-light-state-hover-surface)] data-[disabled]:opacity-[var(--fortis-semantic-light-state-disabled-opacity)]", item.destructive && "text-[var(--fortis-semantic-light-status-danger-text)]")} disabled={item.disabled} key={item.id} onSelect={item.onSelect}>{item.checked !== undefined ? <span aria-hidden="true" className="w-4">{item.checked ? <Icon decorative name="action.confirm" size={14} /> : null}</span> : null}{item.label}</DropdownPrimitive.Item>)}</DropdownPrimitive.Content></DropdownPrimitive.Portal></DropdownPrimitive.Root>; }

export interface PopoverProps { trigger: ReactNode; children: ReactNode; title?: string; open?: boolean; onOpenChange?: (open: boolean) => void; }
export function Popover({ children, onOpenChange, open, title, trigger }: PopoverProps) { const titleId = useId(); return <PopoverPrimitive.Root onOpenChange={onOpenChange} open={open}><PopoverPrimitive.Trigger asChild>{trigger}</PopoverPrimitive.Trigger><PopoverPrimitive.Portal><PopoverPrimitive.Content aria-labelledby={title ? titleId : undefined} className="z-[var(--fortis-primitive-z-index-popover)] max-w-[min(22.5rem,calc(100vw-2rem))] rounded-[var(--fortis-radii-panel)] border border-[var(--fortis-semantic-light-border-default)] bg-[var(--fortis-semantic-light-background-surface)] p-4 shadow-[var(--fortis-elevation-overlay)]">{title ? <h2 className="mb-2 text-sm font-semibold" id={titleId}>{title}</h2> : null}{children}<PopoverPrimitive.Arrow className="fill-[var(--fortis-semantic-light-background-surface)]" /></PopoverPrimitive.Content></PopoverPrimitive.Portal></PopoverPrimitive.Root>; }

const modalSize = { sm: "max-w-[30rem]", md: "max-w-[40rem]", lg: "max-w-[55rem]" } as const;
export interface ModalProps { open: boolean; onOpenChange: (open: boolean) => void; title: string; description?: string; children: ReactNode; footer?: ReactNode; size?: keyof typeof modalSize; dismissible?: boolean; }
export function Modal({ children, description, dismissible = true, footer, onOpenChange, open, size = "md", title }: ModalProps) { const titleId = useId(); const descriptionId = useId(); return <Dialog.Root onOpenChange={onOpenChange} open={open}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[var(--fortis-primitive-z-index-modal)] bg-[var(--fortis-component-overlay-backdrop)]" /><Dialog.Content aria-describedby={description ? descriptionId : undefined} aria-labelledby={titleId} className={cn("fixed left-1/2 top-1/2 z-[calc(var(--fortis-primitive-z-index-modal)+1)] grid max-h-[calc(100dvh-2rem)] w-[calc(100vw-2rem)] -translate-x-1/2 -translate-y-1/2 grid-rows-[auto_minmax(0,1fr)_auto] overflow-hidden rounded-[var(--fortis-component-overlay-radius)] border border-[var(--fortis-component-overlay-border)] bg-[var(--fortis-component-overlay-surface)] shadow-[var(--fortis-component-overlay-elevation)] outline-none", modalSize[size])}><header className="flex items-start justify-between gap-4 border-b border-[var(--fortis-semantic-light-border-default)] p-5"><div><Dialog.Title className="text-lg font-semibold" id={titleId}>{title}</Dialog.Title>{description ? <Dialog.Description className="mt-1 text-sm text-[var(--fortis-semantic-light-text-secondary)]" id={descriptionId}>{description}</Dialog.Description> : null}</div>{dismissible ? <Dialog.Close asChild><IconButton icon="action.close" label="Закрыть диалог" size="sm" variant="quiet" /></Dialog.Close> : null}</header><div className="min-h-0 overflow-y-auto p-5">{children}</div>{footer ? <footer className="flex flex-wrap justify-end gap-2 border-t border-[var(--fortis-semantic-light-border-default)] p-4">{footer}</footer> : null}</Dialog.Content></Dialog.Portal></Dialog.Root>; }

const drawerSize = { sm: "w-[min(22.5rem,calc(100vw-1rem))]", md: "w-[min(30rem,calc(100vw-1rem))]", lg: "w-[min(40rem,calc(100vw-1rem))]" } as const;
export interface DrawerProps { open: boolean; onOpenChange: (open: boolean) => void; title: string; children: ReactNode; footer?: ReactNode; side?: "right" | "left"; size?: keyof typeof drawerSize; dismissible?: boolean; }
export function Drawer({ children, dismissible = true, footer, onOpenChange, open, side = "right", size = "md", title }: DrawerProps) { const titleId = useId(); return <Dialog.Root onOpenChange={onOpenChange} open={open}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[var(--fortis-primitive-z-index-modal)] bg-[var(--fortis-component-overlay-backdrop)]" /><Dialog.Content aria-labelledby={titleId} className={cn("fixed inset-y-0 z-[calc(var(--fortis-primitive-z-index-modal)+1)] grid max-h-dvh grid-rows-[auto_minmax(0,1fr)_auto] border-[var(--fortis-component-overlay-border)] bg-[var(--fortis-component-overlay-surface)] shadow-[var(--fortis-component-overlay-elevation)] outline-none", drawerSize[size], side === "right" ? "right-0 border-l" : "left-0 border-r")}><header className="flex items-center justify-between gap-4 border-b border-[var(--fortis-semantic-light-border-default)] p-5"><Dialog.Title className="text-lg font-semibold" id={titleId}>{title}</Dialog.Title>{dismissible ? <Dialog.Close asChild><IconButton icon="action.close" label="Закрыть панель" size="sm" variant="quiet" /></Dialog.Close> : null}</header><div className="min-h-0 overflow-y-auto p-5">{children}</div>{footer ? <footer className="border-t border-[var(--fortis-semantic-light-border-default)] p-4">{footer}</footer> : null}</Dialog.Content></Dialog.Portal></Dialog.Root>; }

export interface ToastProps { open: boolean; onOpenChange: (open: boolean) => void; title: string; description?: string; tone?: "neutral" | Exclude<StatusTone, "neutral">; action?: ReactNode; duration?: number | null; }
export function Toast({ action, description, duration = 5000, onOpenChange, open, title, tone = "neutral" }: ToastProps) { const toneClass = tone === "neutral" ? "border-[var(--fortis-semantic-light-border-default)] bg-[var(--fortis-semantic-light-background-surface)]" : toneClasses[tone]; return <ToastPrimitive.Provider duration={duration ?? undefined}><ToastPrimitive.Root className={cn("grid w-[min(26.25rem,calc(100vw-2rem))] gap-1 rounded-[var(--fortis-radii-panel)] border p-4 shadow-[var(--fortis-elevation-overlay)]", toneClass)} onOpenChange={onOpenChange} open={open}><ToastPrimitive.Title className="text-sm font-semibold">{title}</ToastPrimitive.Title>{description ? <ToastPrimitive.Description className="text-[0.8125rem] text-[var(--fortis-semantic-light-text-secondary)]">{description}</ToastPrimitive.Description> : null}{action ? <div className="mt-2">{action}</div> : null}<ToastPrimitive.Close aria-label="Закрыть уведомление" className="absolute right-2 top-2 grid size-8 place-items-center rounded hover:bg-black/5"><Icon decorative name="action.close" size={14} /></ToastPrimitive.Close></ToastPrimitive.Root><ToastPrimitive.Viewport className="fixed right-4 top-4 z-[var(--fortis-primitive-z-index-toast)] outline-none" /></ToastPrimitive.Provider>; }

const stateContainer = "grid justify-items-start gap-3 rounded-[var(--fortis-radii-panel)] border border-[var(--fortis-semantic-light-border-default)] bg-[var(--fortis-semantic-light-background-surface)] p-6 text-left";
export interface StateProps { title: string; description?: ReactNode; action?: ReactNode; }
export function EmptyState({ action, description, title }: StateProps) { return <section className={stateContainer}><Icon className="text-[var(--fortis-semantic-light-text-secondary)]" decorative name="action.search" size={28} /><div><h2 className="font-semibold">{title}</h2>{description ? <p className="mt-1 text-sm text-[var(--fortis-semantic-light-text-secondary)]">{description}</p> : null}</div>{action}</section>; }
export function LoadingState({ label = "Загрузка", kind = "inline" }: { label?: string; kind?: "inline" | "skeleton" | "overlay" }) { return kind === "skeleton" ? <div aria-hidden="true" className="grid gap-3"><span className="h-5 w-2/5 animate-pulse rounded bg-[var(--fortis-semantic-light-background-muted)]" /><span className="h-10 w-full animate-pulse rounded bg-[var(--fortis-semantic-light-background-muted)]" /></div> : <div aria-busy="true" aria-live="polite" className={cn("flex items-center gap-2 text-sm text-[var(--fortis-semantic-light-text-secondary)]", kind === "overlay" && "absolute inset-0 z-10 justify-center bg-white/80")}><Icon className="animate-spin motion-reduce:animate-none" decorative name="status.loading" size={18} />{label}</div>; }
export function ErrorState({ action, description, title }: StateProps) { return <section className={stateContainer} role="alert"><Icon className="text-[var(--fortis-semantic-light-status-danger-text)]" decorative name="status.error" size={28} /><div><h2 className="font-semibold">{title}</h2>{description ? <p className="mt-1 text-sm text-[var(--fortis-semantic-light-text-secondary)]">{description}</p> : null}</div>{action}</section>; }
export function SuccessState({ action, description, title }: StateProps) { return <section aria-live="polite" className={stateContainer}><Icon className="text-[var(--fortis-semantic-light-status-success-text)]" decorative name="status.success" size={28} /><div><h2 className="font-semibold">{title}</h2>{description ? <p className="mt-1 text-sm text-[var(--fortis-semantic-light-text-secondary)]">{description}</p> : null}</div>{action}</section>; }

export function ToastAction({ children, onClick }: { children: ReactNode; onClick?: () => void }) { return <Button onClick={onClick} size="sm" variant="quiet">{children}</Button>; }
