/**
 * Канонические пользовательские строки GIS-прототипа.
 *
 * Названия провайдеров карт и принятые аббревиатуры остаются без перевода.
 * Компоненты получают copy отсюда, чтобы runtime не смешивал языки.
 */
export const prototypeRu = {
  workspace: {
    name: "ГИС-рабочее пространство",
    studioName: "Студия конфигурации защиты",
    mapTitle: "Моя карта",
    previewShortName: "ПРОСМОТР",
    locked: "Заблокирован",
  },
  tree: {
    eyebrow: "ГИС-рабочее пространство",
    title: "Структура проекта",
    searchLabel: "Поиск в структуре",
    searchPlaceholder: "Объект или эшелон",
    protectedObject: "Объект защиты",
    fallbackObject: "Средство защиты",
    hiddenOnMap: "Скрыт на карте",
    shownOnMap: "На карте",
    warning: "Есть предупреждение",
    projectContent: "Эшелоны и объекты проекта",
    baseObjectGlyph: "О",
    objectCount: (count: number) => {
      const mod10 = count % 10;
      const mod100 = count % 100;
      if (mod10 === 1 && mod100 !== 11) return `${count} объект`;
      if (mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)) return `${count} объекта`;
      return `${count} объектов`;
    },
    echelonDetail: (isActive: boolean, isHidden: boolean, objectCount: string) =>
      `${isActive ? "Активный · " : ""}${isHidden ? "скрыт" : "видим"} · ${objectCount}`,
  },
  inspector: {
    context: "Контекст",
    title: "Инспектор",
    emptyTitle: "Ничего не выбрано",
    emptyDescription:
      "Выберите объект на карте или в структуре проекта, чтобы посмотреть параметры и предупреждения.",
    loading: "Загрузка контекста…",
    selectedEchelon: "Выбранный эшелон",
    echelonTitle: "Инспектор эшелона",
    selectedObject: "Выбранный объект",
    objectTitle: "Инспектор объекта",
    close: "Закрыть инспектор",
    summary: "Сводка",
    quantity: "Количество",
    cost: "Стоимость",
    coverage: "Покрытие",
    type: "Тип",
    objectControls: "Управление объектом",
    objectQuantity: "Количество объектов",
    decreaseQuantity: "Уменьшить количество объектов",
    increaseQuantity: "Увеличить количество объектов",
    objectStatus: "Статус объекта",
    coordinates: "Координаты",
    latitude: "Широта",
    longitude: "Долгота",
    visibility: "Видимость",
    objects: "Объекты",
    code: "Код",
    order: "Порядок",
    active: "Активен",
    inactive: "Выключен",
    maintenance: "На обслуживании",
    planned: "Запланирован",
    mobile: "Мобильный",
    stationary: "Стационарный",
    hidden: "Скрыт",
    visible: "Виден",
    visibleOnMap: "Виден на карте",
    shownOnMap: "Показан на карте",
    showOnMap: "Показать на карте",
    hideOnMap: "Скрыть на карте",
    missingEchelon: "Эшелон больше не доступен.",
    missingObject: "Объект больше не доступен.",
    geometryConflict: "Геометрия пересекается с ограничением",
    coverageConflict: "Покрытие конфликтует с соседним объектом",
    terrainConflict: "Требуется проверить рельеф",
    metersSuffix: " м",
    costMln: (formattedValue: string) => `${formattedValue} млн ₽`,
  },
  library: {
    role: "Добавление объектов",
    eyebrow: "Библиотека средств защиты",
    noEchelon: "Эшелон не выбран",
    context: (code: string, name: string) => `Добавить в ${code} · ${name}`,
    emptyTitle: "Средства защиты не найдены",
    emptyDescription: "Измените поисковый запрос или очистите фильтры библиотеки.",
    searchLabel: "Поиск по библиотеке средств защиты",
    searchPlaceholder: "Найти средство...",
    expandPanel: "Развернуть библиотеку",
    collapsePanel: "Свернуть библиотеку",
    management: "Управление карточками",
    count: (count: number) => `${count} средств в текущей библиотеке`,
    refresh: "Обновить каталог с сервера",
    createAsset: "Создать средство защиты",
    editAsset: "Редактировать выбранное средство",
    loading: "Загрузка библиотеки",
    loadError: "Не удалось загрузить библиотеку",
    actionError: "Не удалось выполнить действие",
    createAria: "Создание средства защиты",
    editAria: "Редактирование средства защиты",
    newAsset: "Новое средство",
    assetCard: "Карточка средства",
    cancelAndReturn: "Отменить и вернуться в библиотеку",
    name: "Название",
    category: "Категория",
    coverageType: "Тип покрытия",
    protectionType: "Тип защиты",
    recommendedEchelons: "Рекомендуемые эшелоны",
    recommendedEchelonsPlaceholder: "L2, L3",
    priceMln: "Цена, млн ₽",
    radiusKm: "Радиус, км",
    angleDegrees: "Угол, °",
    maxDistanceKm: "Максимальная дальность, км",
    description: "Описание",
    publicCatalog: "Общий каталог",
    publicCatalogDescription: "Карточка доступна всем предприятиям.",
    enterpriseId: "Идентификатор предприятия",
    assetUsed: "Средство размещено на карте",
    deleteAsset: "Удалить средство защиты",
    cancel: "Отмена",
    create: "Создать",
    save: "Сохранить",
    nameRequired: "Укажите название средства защиты.",
    saveError: "Не удалось сохранить карточку на сервере.",
    assetUsedDeleteError: "Средство уже размещено на карте. Удаление заблокировано.",
    deleteError: "Не удалось удалить карточку на сервере.",
    savedMessage: (name: string) => `${name} сохранено в библиотеке`,
    deletedMessage: (name: string) => `${name} удалено из библиотеки`,
    categoryOptions: [
      { value: "detection", label: "Обнаружение" },
      { value: "classification", label: "Классификация" },
      { value: "jamming", label: "РЭБ" },
      { value: "spoofing", label: "Спуфинг" },
      { value: "kinetic", label: "Поражение" },
      { value: "interceptor", label: "Перехват" },
      { value: "passive-protection", label: "Пассивная защита" },
      { value: "engineering-protection", label: "Инженерная защита" },
      { value: "infrastructure", label: "Инфраструктура" },
      { value: "command-center", label: "Командный центр" },
      { value: "early-warning", label: "Раннее предупреждение" },
      { value: "software", label: "ПО" },
      { value: "external-service", label: "Внешний сервис" },
    ],
    coverageTypeOptions: [
      { value: "circle", label: "Круг" },
      { value: "sector", label: "Сектор" },
      { value: "line", label: "Линия" },
      { value: "polygon", label: "Полигон" },
      { value: "none", label: "Нет" },
    ],
  },
  echelons: {
    overviewRole: "Быстрый обзор эшелонов",
    overviewTitle: "Эшелоны проекта",
    activeContext: (code: string, name: string) => `Активный эшелон: ${code} · ${name}`,
    emptyTitle: "В этом эшелоне пока нет объектов",
    emptyDescription: "Перетащите средство из библиотеки на карту.",
    conflict: "Есть конфликт",
    selected: "Выбран",
    visible: "Виден",
    hidden: "Скрыт",
    objectsPanelDescription: "Быстрый список объектов активного эшелона.",
    overviewAria: "Обзор эшелонов",
    summary: (count: number, maximum: number) => `${count} из ${maximum}`,
    activeHeader: (code: string, objectCount: string) => `Активный: ${code} · ${objectCount}`,
    showAllObjects: "Все объекты",
    showActiveOnly: "Только активный",
    showAllObjectsTitle: "Показать объекты всех эшелонов на карте",
    showActiveOnlyTitle: "Скрыть объекты других эшелонов на карте",
    add: "Добавить эшелон",
    maximum: (maximum: number) => `Максимум ${maximum} эшелонов`,
    expandPanel: "Развернуть панель эшелонов",
    collapsePanel: "Свернуть панель эшелонов",
    scrollLeft: "Прокрутить эшелоны влево",
    scrollRight: "Прокрутить эшелоны вправо",
    openObjects: "Открыть объекты эшелона",
    edit: "Настроить эшелон",
    delete: "Удалить эшелон",
    deleteUnavailable: (reason: string) => `Удалить эшелон · ${reason}`,
    select: "Выбрать",
    show: "Показать эшелон",
    hide: "Скрыть эшелон",
    openMenu: "Открыть меню эшелона",
    cannotDeleteLast: "Последний эшелон удалить нельзя.",
    cannotDeleteWithObjects: "Нельзя удалить: в эшелоне есть объекты.",
    deleteRequiresConfirmation: "Удаление доступно только после подтверждения.",
    objectsPanel: "Объекты эшелона",
    expandCard: "Развернуть карточку",
    collapseCard: "Свернуть карточку",
    closeCard: "Закрыть карточку",
  },
  cards: {
    map: "Карта",
    zone: "Зона",
    drag: "Перетащите",
    draw: "Нарисовать",
    onMap: "На карте",
    sites: "Участков",
    basePostCost: "Базовая стоимость поста",
    postType: "Тип поста",
    personnel: "Личный состав",
    accountability: "Подотчётность",
    weapons: "Оружие",
    sector: "Сектор",
    enterCoordinates: "Ввести координаты",
    drawArea: "Нарисовать область",
  },
  baseMap: {
    internalTitle: "Внутренняя подложка",
    internalVectorDescription: "Локальная или собственная подложка для закрытого контура.",
    internalRasterDescription: "Собственная растровая или WMTS-подложка для закрытого контура.",
    internalOfflineDescription: "Офлайн-подложка Fortis для закрытого контура.",
    openFreeMapDescription: "Открытая векторная подложка на основе данных OSM для демо и разработки.",
    osmDescription: "Резервная растровая подложка для демо и разработки; не является production-зависимостью.",
    topographicTitle: "Топографическая",
    topographicDescription: "Настраиваемая топографическая подложка для демо и планирования.",
    satelliteTitle: "Спутниковая демо-подложка",
    satelliteDescription: "Дополнительный спутниковый или ортофото-источник после правовой проверки.",
    noSources: "Для текущей среды Fortis нет доступных источников карты.",
  },
} as const;
